pub(crate) mod appender;
pub mod client_context;
pub(crate) mod connection;
pub mod data_chunk;
pub(crate) mod error_data;
/// Bound-expression RAII + constant folding, used by scalar-function bind (`udf`).
#[cfg(feature = "udf")]
pub mod expression;
pub(crate) mod extracted;
pub mod instance_cache;
pub mod owned_value;
pub mod owned_vector;
pub(crate) mod pending;
pub mod profiling;
pub mod result;
pub mod row;
pub mod selection_vector;
pub(crate) mod statement;
pub mod table_description;
pub mod task_state;
