[package]
name                  = "better-duck-core"
version.workspace     = true
edition.workspace     = true
license.workspace     = true
description.workspace = true
repository.workspace  = true
homepage.workspace    = true
keywords.workspace    = true
categories.workspace  = true
readme.workspace      = true

[lints]
workspace = true

[dependencies]
better-duck-sys = { workspace = true }
log           = { workspace = true }
parking_lot   = { workspace = true }
chrono        = { workspace = true, optional = true }
strum         = { workspace = true, features = ["derive"] }
rust_decimal  = { workspace = true, features = ["macros"], optional = true }
r2d2          = { workspace = true, optional = true }
tokio         = { workspace = true, features = ["rt"], optional = true }
better-duck-macros = { path = "../better-duck-macros", version = "0.1.0-beta.4", optional = true }

[features]
default         = ["chrono", "decimal"]
json            = ["better-duck-sys/json"]
parquet         = ["better-duck-sys/parquet"]
chrono          = ["dep:chrono"]
decimal         = ["dep:rust_decimal"]
pool            = ["dep:r2d2"]
async           = ["dep:tokio"]
udf             = ["dep:better-duck-macros"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dev-dependencies]
tempfile   = "3.27.0"
criterion  = { version = "0.8.2", features = ["html_reports"] }
tokio      = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "time"] }
uuid = "1.24.0"
trybuild = "1.0"

[[bench]]
name    = "my_benchmark"
harness = false
