// SPDX-License-Identifier: MIT OR Apache-2.0
//! Vendored DuckDB C API bindings for the `better-duck` workspace.
//!
//! This crate replaces the external `libduckdb-sys` dependency: DuckDB's C++
//! source is vendored directly in this crate (`vendor/duckdb.tar.gz`,
//! compiled from source by `build.rs` on every build — there is no toggle for
//! this, unlike upstream's `bundled` feature, since this crate exists
//! specifically to own that source), and the FFI `bindings`
//! are pregenerated and checked in rather than produced by
//! `bindgen` at consumer build time. See `xtask/src/main.rs` (workspace
//! root) for the maintainer-only regeneration process.
#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]
#![allow(missing_docs, clippy::missing_safety_doc, clippy::undocumented_unsafe_blocks)]

// Default (linked) mode: DuckDB is compiled into this crate and every `duckdb_*` is a
// direct `extern "C"` symbol.
#[cfg(not(feature = "loadable-extension"))]
mod bindings;
mod error;

// Loadable-extension mode: this crate links NO DuckDB. A `.duckdb_extension` is loaded
// *into* a running DuckDB, so each `duckdb_*` is a wrapper dispatching through the host's
// `duckdb_ext_api_v1` function-pointer table, populated at load time by
// `duckdb_rs_extension_api_init`. Generated by
// `cargo run -p xtask -- upgrade-duckdb <tag> --loadable-bindings` followed by
// `cargo run -p xtask -- gen-loadable-wrappers`.
#[cfg(feature = "loadable-extension")]
#[path = "bindings_loadable.rs"]
mod bindings;

pub use bindings::*;
pub use error::{DuckDBError, DuckDBSuccess, Error};

/// The upstream DuckDB release tag this crate's vendored source and bindings
/// were generated from (e.g. `"v1.5.5"`), set by `build.rs` from the vendored
/// archive's own `manifest.json`.
pub const DUCKDB_VENDORED_VERSION: &str = env!("DUCKDB_VENDORED_VERSION");
